# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PalmMedia - Sociální Sítě, Podcasty, Distribuce obsahu
description: Specializujeme se na tvorbu marketingových kampaní na sociálních sítích, video & foto produkci, vývoj webových stránek a branding vašeho projektu.
keywords: marketing, tvorba webových stránek, video produkce, fotograf, vytvořit web, reklama, reklama na facebooku, reklama na instagramu, mediální agentura, digitální agentura, styvekdrtic, tvorba obsahu, šíření obsahu, Jiri Stepanek
author: palmmedia.co
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://palmmedia.cz/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
